# Generated by Django 5.0 on 2023-12-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='path_to_default_image.jpg', upload_to='post_img'),
        ),
    ]
