# Generated by Django 5.0 on 2023-12-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_post_post_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
